import "./globals.css";
import "rsuite/dist/rsuite-no-reset.min.css";

import Footer from "../components/Footer";
import Hamburger from "@/components/Hamburger";

export const metadata = {
  title: {
    default: "Lukui",
    template: "%s | Lukui",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        <Hamburger />
        {children}

        <Footer />
      </body>
    </html>
  );
}
