import "./globals.css";
import "rsuite/dist/rsuite-no-reset.min.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: {
    default: "Lukui",
    template: "%s | Lukui",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header> */}
        <Header />
        {children}
        {/* <footer style={{ backgroundColor: "darkgreen", padding: "1rem" }}>
          <p>Footer</p>
        </footer> */}
        <Footer />
      </body>
    </html>
  );
}
